@startuml
package "command" #DDDDDD{

    class Client{}

    interface  command{
        +exec():void
        +undo():void
    }

     class LightOnCommand implements command{
        +exec():void
        +undo():void 
     }

     class LightOffCommand implements command{
        +exec():void
        +undo():void 
     }
     class NoCommand implements command{
     }

    note Top of NoCommand
     <i>NoCommand 表示空命令 </i>
     <i>對於簡化操作有幫助，可以省掉對空的判斷</i>
    end note

    class LightReciver{
        +on():void
        +off():void
    }

     LightReciver --o LightOnCommand
     LightReciver --o LightOffCommand

     class RemoveController{
        -onCommands:command[]
        -offCommands:command[]
     }

     command --o RemoveController

     Client --> RemoveController
     Client --> LightReciver
     Client --> LightOnCommand
     Client --> LightOffCommand
}
@enduml
